name: stadtnavi_app
description: A Flutter Application for the stadtnavi Herrenberg
repository: https://github.com/stadtnavi/stadtnavi-app
homepage: https://stadtnavi.de/
issue_tracker: https://github.com/stadtnavi/stadtnavi-app/issues

publish_to: "none"

version: 1.3.0+40

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3

  flutter:
    sdk: flutter

  graphql: ^4.0.1
  lint: ^1.5.3
  mqtt_client: ^9.3.1
  scrollable_panel: ^0.4.1
  trufi_core:
    git:
      url: https://github.com/trufi-association/trufi-core.git
      ref: 2.5.2

  vector_tile:
    git:
      url: https://github.com/trufi-association/dart-vector-tile.git
      ref: fc916fd067cb4e64ab782e6249b4e296c7dba913

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/cfg/
    - assets/data/
    - assets/data/hb-layers/
    - assets/images/
